spring:
    datasource:
        url: jdbc:postgresql://localhost:5010/school
        username: w0lin
        password: admin

    jpa:
        hibernate:
            ddl-auto: create-drop
        properties: 
            hibernate: 
            dialect: org.hibernate.dialect.PostgreSQLDialect
            format-sql: true
        show-sql: true

    main:
        web-application-type: servlet

    security:
        user:
            name: "admin"
            password: "admin"
    